destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    rdiscount
permalink:   date
images:    http://i905.photobucket.com/albums/ac259/virtix
sp:    <p>&nbsp;</p>