destination:     ./_site
auto:            true
lsi:             false
server_port:     4000
pygments:        true
markdown:        rdiscount
permalink:       date
images:          http://i905.photobucket.com/albums/ac259/virtix
_resources:      http://mxunit.s3.amazonaws.com
resources:
sp:    <p>&nbsp;</p>